### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by DrakeLoco** [CalaMariGold/Rebirth-Of-The-Night#252] opened 2020-04-16 03:25 UTC
**Describe the crash**
We were in an invasion in which I used my fire dragon to defend the base, I live in a biome of eucalyptus trees, I think the crash occurred one after another by the fire of the dragon in the wood or the leaves, we opened the server repeatedly until it cleaned the wood that was burning and stopped crashing.

**To Reproduce**

Use the dragon's breath to burn eucalyptus trees
**Crash Log**
https://pastebin.com/WXQMVpzq

[crash-2020-04-15_22.48.59-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4484732/crash-2020-04-15_22.48.59-server.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: Server 
 - Version the world was created on: 2.76

**Comment by CalaMariGold** [comment] 2020-04-18 21:36
Duplicate of #54

**Closed by CalaMariGold** 2020-04-18 21:36 UTC
