### ISSUE TITLE
[CRASH] Due to Dynamic Trees on game startup.

### ISSUE THREAD

**Issue by clowned187** [CalaMariGold/Rebirth-Of-The-Night#106] opened 2020-03-04 00:33 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
After starting the modpack from twitch everything loads fine, but once I select my world and the game loads it immediately says "shutting down internal servers" and produces a crash due to "Dynamic Trees"

**To Reproduce**
Select world and start game from main menu.

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
https://paste.dimdev.org/atahitenoh.mccrash
**Info (please complete the following information):**
 - Modpack Version: 2.76
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76 

**Additional context**
Not sure to be honest, been playing this for a bit now and never had an issue.

**Comment by clowned187** [comment] 2020-03-04 01:06
![2020-03-03_19 22 27](https://user-images.githubusercontent.com/61764606/75834595-6cc5e500-5d8a-11ea-8f46-fd656c863eff.png)

**Comment by CalaMariGold** [comment] 2020-03-04 21:09
This is a connected textures issue. Just start the world again and it should work.

**Comment by clowned187** [comment] 2020-03-06 05:30
All set, Thank you.

**Comment by Lucaya88** [comment] 2020-03-14 10:52
I get the same crash, over and over again. Re-loading the world doesn't seems to work at all or how is this meant to work?
I tried to load the world again, also restarting MC and doing it again does not fix it.

**Comment by kil0byt3** [comment] 2020-04-09 17:40
Duplicate of https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/128

**Closed by kil0byt3** 2020-04-09 17:40 UTC
