### ISSUE TITLE
[BUG] Cursed bead doesn't go in filtered hopper

### ISSUE THREAD

**Issue by ShadowFreeze** [CalaMariGold/Rebirth-Of-The-Night#267] opened 2020-04-19 20:06 UTC
**Describe the bug**
When tossing a cursed bead into a filtered hopper (with soul sand filter), it sits on top, and does not go into the hopper.

**To Reproduce**
toss a cursed bead onto a filtered hopper with a soul sand filter, powered or powered, with or without an urn underneath.

**Expected behavior**
It is meant to be absorbed by the hopper, and then spit back out as soul flux. (as shown in JEI)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Comment by democat3457** [comment] 2020-05-08 04:54
Could the reason be because of NBT?

**Comment by democat3457** [comment] 2020-05-14 18:42
dupe of #334

**Closed by democat3457** 2020-05-14 18:42 UTC
