### ISSUE TITLE
Consistent Rats/Living Enchantment Crash when attacked By Pied Piper

### ISSUE THREAD

**Issue by KyoZaChi** [CalaMariGold/Rebirth-Of-The-Night#152] opened 2020-03-22 06:17 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
When ever I am attacked by the pied pipers rats in the twilight forest this crash occurs, it says the culprits are Living Enchantment and Rats

**To Reproduce**
Get attacked by a Pied piper and its rats

**Crash Log**
https://paste.dimdev.org/qaganiriri.mccrash

**Info (please complete the following information):**
 - Modpack Version:  2.67.2
 - Singleplayer
 - Version the world was created on: 2.67.2

**Additional context**
Seems to happen more frequently when the rats are withered by Dark's Edge

**Comment by KyoZaChi** [comment] 2020-03-22 08:29
Investigating the crash more have some additional notes, thorns seems to proc the withering debuff from dark's edge it seems occasionally that just randomly causes me to crash

**Comment by CalaMariGold** [comment] 2020-03-31 06:10
Duplicate of #140

**Closed by CalaMariGold** 2020-03-31 06:10 UTC
