### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by unicornbloods** [CalaMariGold/Rebirth-Of-The-Night#356] opened 2020-05-21 19:11 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Birch tree missing texture

**To Reproduce**
Download and run ROTN 2.77.4

**Expected behavior**
Tree not broken

**Screenshots**
<a href="https://ibb.co/SPNdbrL"><img src="https://i.ibb.co/g3yPNVn/2020-05-21-09-07.png" alt="2020-05-21-09-07" border="0"></a>

**Info (please complete the following information):**
 - Modpack Version: 2.77.4
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77.4

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
TTRRREEEEEESSSSS

**Comment by democat3457** [comment] 2020-05-21 19:12
Have you tried restarting your game? It usually fixes texture issues.

**Comment by kil0byt3** [comment] 2020-05-24 21:07
Duplicate of #70 - I think this might be fixed in newer DT versions as well - it's so sporadic that it's nearly impossible to track down

**Closed** 2020-05-24 21:07 UTC
