### ISSUE TITLE
Soapstone slabs. When u mine them back up they become Komatite slabs[BUG]

### ISSUE THREAD

**Issue by Garfink** [CalaMariGold/Rebirth-Of-The-Night#382] opened 2020-06-12 05:54 UTC
**Describe the bug**
Soapstone slabs. When u mine them back up they become Komatite slabs

**To Reproduce**
Soapstone slabs. When u mine them back up they become Komatite slabs

**Expected behavior**
Soapstone slabs. When u mine them back up they are Soapstone slabs

**Info (please complete the following information):**
 - Modpack Version: 2.78 on your github, version around 3 weeks ago.
 - Server or Singleplayer: Server
 - Version the world was created on: Same as above.

**Additional context**
May have  been fixed already, but just wanted you guys to know.

**Comment by democat3457** [comment] 2020-06-12 14:49
Duplicate of #362

**Closed by democat3457** 2020-06-12 14:49 UTC
