### ISSUE TITLE
[CRASH] Zombie with Steve skin cause crash.

### ISSUE THREAD

**Issue by CereBrawl404** [CalaMariGold/Rebirth-Of-The-Night#284] opened 2020-04-25 07:54 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
This is the second time ive had this crash on 2 seperate worlds.
A zombie with the original minecraft steve skin spawned during the night and looking at him directly caused the screen to go black and the game freezes forever.

**To Reproduce**
He spawned during a normal night post nether. (on both occasions it was post nether)

**Crash Log**
[crash-2020-04-25_03.37.01-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4532580/crash-2020-04-25_03.37.01-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
I am using optifine with shaders.

Thanks for the pack!

**Comment by democat3457** [comment] 2020-04-25 15:25
Did anyone die and cause a zombie player to spawn? It seems like the bug occurs when a zombie player spawns without a player profile, causing a null name for the zombie player. When you look at the zombie, the Neat mod tries to find the display name of the zombie to display to you. However, it doesn't find one and crashes. This is probably a mod bug... one with the Zombie_Players mod.

**Comment by SandwichHorror** [comment] 2020-04-26 04:46
duplicate of #74

**Closed by SandwichHorror** 2020-04-26 04:46 UTC
