### ISSUE TITLE
[CRASH] Server crash when sawing (BetterWithMods) BoP "vertical slab"

### ISSUE THREAD

**Issue by Insane96** [CalaMariGold/Rebirth-Of-The-Night#275] opened 2020-04-22 18:36 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Putting a BoP vertical slab by the side of a saw to make the smaller version crashed the server

**To Reproduce**
1. Make a working saw with a Windmill
2. Put a Redwood plank by a saw to saw
3. Saw the product again
4. Crash

**Crash Log**
https://pastebin.com/raw/nhCKzzFZ

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77

**Comment by democat3457** [comment] 2020-04-23 03:07
Hm it seems like the crash report includes fire spreading? What, if anything, was on fire?

**Comment by Insane96** [comment] 2020-04-23 07:20
There was fire nearby under a cauldron, but I think was too far away.

**Comment by democat3457** [comment] 2020-04-24 01:43
Well apparently it wasn't too far away. I tested it on singleplayer (set a redwood siding on fire, put another siding next to it) and it crashed the internal server. Apparently it identified BoP, BWM, and Controlled Burn as the source of the error.
[crash-2020-04-23_20.41.01-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4526173/crash-2020-04-23_20.41.01-server.txt)

**Comment by SandwichHorror** [comment] 2020-04-24 01:46
Duplicate of #69

**Closed by SandwichHorror** 2020-04-24 01:46 UTC
