### ISSUE TITLE
[BUG] Balloon and Jump Height Quality Conflict

### ISSUE THREAD

**Issue by Areorah** [CalaMariGold/Rebirth-Of-The-Night#380] opened 2020-06-10 22:50 UTC
**Describe the bug**
The balloon and extra jump height from armor doesn't stack.

**To Reproduce**
Wear a balloon and something with extra jump height armor (like springy quality.)

**Expected behavior**
I should be jumping at least the height of the balloon (plus the little extra), but instead it ignores the balloon and only jumps via the armor extra. The balloon allows jumping up 3 blocks, while with both on I am only able to jump up 2 blocks.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.5

**Additional context**

**Comment by democat3457** [comment] 2020-06-11 13:59
Duplicate of #112

**Closed by democat3457** 2020-06-11 13:59 UTC
Labels: duplicate
