### ISSUE TITLE
[CRASH] Living Enchantment + Vespa Crash

### ISSUE THREAD

**Issue by Redmikeisback** [CalaMariGold/Rebirth-Of-The-Night#140] opened 2020-03-19 17:54 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
We started the server and were killing mobs when the server crashed. In the crash reports, it says a different entity caused it each time.

**To Reproduce**
Spawn in kill mobs 

**Crash Log**
1st crash
https://pastebin.com/KiQxWk2C

2nd crash 
https://pastebin.com/A425aE6N

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer:
 - Version the world was created on: ?

**Additional context**
I have darks edge with the living enchant both said suspected mods living enchant possibly the problem unsure, because it was working fine the day before.

**Comment by CalaMariGold** [comment] 2020-03-20 18:17
From reading the crash, it seems to occur when you attack a Vespa with the a sword enchanted with Living. I'm unsure how we would fix this but I'll do some testing if I have time.

**Comment by Redmikeisback** [comment] 2020-03-20 19:00
Thank you I'll be sure not to do that XD

**Comment by CalaMariGold** [comment] 2020-03-31 06:10
"Investigating the crash more have some additional notes, thorns seems to proc xp gain for darks edge not sure if that leads to crash but when small creatures like rats, parasites attack me and thorns procs while i hold darks edge i crash" - From #152

**Comment by democat3457** [comment] 2020-04-25 01:55
From looking into the source for Living Enchantment, it seems like the illegal arg error was caused by a mistyped ending array index (if the random number was 1, it'd crash because it was trying to access `arr[arr.length]`. I've opened a PR with the mod to try and fix it. Not sure if #152 was also caused by an Illegal Arg since I can't see the crash log (the site is down?), so not sure if it's actually a duplicate

**Comment by democat3457** [comment] 2020-05-06 23:36
dupe of #294

**Comment by democat3457** [comment] 2020-05-07 00:05
either #294 or this should be closed, also working on adding personalities but stuff is on another computer so i cant commit rn
bandaid pr here: https://github.com/Clownvin/Living-Enchantment/pull/17

**Comment by democat3457** [comment] 2020-06-03 03:49
Fixed by #325

**Closed by democat3457** 2020-06-03 03:49 UTC
Labels: RotN bug, mod bug, needs testing
