### ISSUE TITLE
[CRASH] Crash while using the Future MC Stonecutter

### ISSUE THREAD

**Issue by ThomBern** [CalaMariGold/Rebirth-Of-The-Night#24] opened 2020-01-16 17:48 UTC
I was trying to make Stone Bricks using the Future MC stone cutter when all of a sudden the game crashed. The crash seemed to happen only when I shift click the output result of the stone cutter (in this case bricks) in my inventory, and doesn't occur when I individually click the output.

I don't know if the crash is a result of the modpack, or just because the stone cutter is buggy, but I'd rather let you know about this issue, just in case.

P.S.: The crash also seems to happen while trying to shift click Gneiss bricks. 

Here's the crash file:

[Stonecutter crash.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4072850/Stonecutter.crash.txt)

**Comment by CalaMariGold** [comment] 2020-01-17 02:50
Can someone else confirm this is an issue? If so, we'll send this report to the FutureMC developers.

**Comment by Spencer92** [comment] 2020-01-17 02:57
I removed the underground biome recipes from the stonecutter and shift-clicking did indeed cause a crash. This was also on 2.73.1 so it isn’t an issue with 2.74. So it looks like the issue isn’t on our end.


Sent from Mail for Windows 10

**Comment by Spencer92** [comment] 2020-01-17 02:59
I removed the underground biome recipes and shift-clicking still crashed. This was also on 2.73.1, so it isn’t a 2.74 problem. So as far as I know it isn’t on our end.

https://paste.dimdev.org/sunupedure.mccrash

Sent from Mail for Windows 10

**Comment by HeyItsKairu** [comment] 2020-01-18 00:46
This issue has already been reported and is planned on being fixed. Duplicate of [Future MC Issue 78](https://github.com/thedarkcolour/Future-MC/issues/78). The date on this issue is 05.11.19, so it has been a couple months since the issue has been reported.

**Comment by kil0byt3** [comment] 2020-04-09 17:07
Fixed in upcoming https://github.com/thedarkcolour/Future-MC/issues/78

**Comment by democat3457** [comment] 2020-05-19 21:07
Leaving it open as a reminder to update futuremc.

**Comment by democat3457** [comment] 2020-05-31 20:42
Fixed with a387e168ff67989230e5b6d2c92517726f70bac0

**Closed by democat3457** 2020-05-31 20:42 UTC
Labels: mod bug, mod update needed
