### ISSUE TITLE
[CRASH] Mining with anything relating to Dungeon Tactic

### ISSUE THREAD

**Issue by blujaythehealer** [CalaMariGold/Rebirth-Of-The-Night#312] opened 2020-05-06 19:58 UTC
[crash-2020-05-06_15.39.10-server.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4589164/crash-2020-05-06_15.39.10-server.txt)
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Crash happens when you mine a block with an item effected by Dungeon Tactic, Either axes or Enchanted pickaxes with the "smelting" enchant.

**To Reproduce**
Have a pickaxe with the smelting enchantment or an axe and mine an ore or log respectively.

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: Both 2.76 and 2.77.1

**Additional context**
This was not an issue until very recently, I've tried reinstalling the pack and it still had the same issue

**Comment by democat3457** [comment] 2020-05-06 20:24
Duplicate of #262

**Comment by democat3457** [comment] 2020-05-07 05:49
Oughta be closed :wink:

**Closed** 2020-05-13 23:23 UTC
