### ISSUE TITLE
[CRASH] Problem with the stonesaw

### ISSUE THREAD

**Issue by SlavvyMcStabby** [CalaMariGold/Rebirth-Of-The-Night#347] opened 2020-05-17 01:43 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
shift using the stonesaw with multiple items crashes the game

**To Reproduce**
hold shift, and use the stonesaw with a stack of stones in hand

**Crash Log**
[crash-2020-05-16_21.24.27-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4639521/crash-2020-05-16_21.24.27-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77.3
 - Server or Singleplayer: singeplayer
 - Version the world was created on: 2.77.3

**Additional context**
claims that MC Future causes the issue. Not crash to desktop

**Comment by kil0byt3** [comment] 2020-05-17 01:51
Thanks! I think this was fixed in latest MCFuture version, I'll verify and let you know if it'll be fixed in the next version of the pack

**Comment by democat3457** [comment] 2020-05-17 16:52
dupe of #24 btw

**Comment by kil0byt3** [comment] 2020-05-19 21:06
^

**Closed by kil0byt3** 2020-05-19 21:06 UTC
Labels: mod bug, needs testing
