### ISSUE TITLE
[CRASH] Caramel Slime breaks player

### ISSUE THREAD

**Issue by mjakim2** [CalaMariGold/Rebirth-Of-The-Night#22] opened 2020-01-16 05:56 UTC
So in 2.74, the new slimes spawn in the afternoon, one of which being the brown slime. I knew that the lemon slime summoned lightning, so I let this one hit me to see its affects. I was forcibly placed on top of it and it started draining health; however, after a couple of seconds, I was kicked from my friend's LAN server, claiming "Invalid move player packet received".

**Comment by CalaMariGold** [comment] 2020-01-17 02:48
Most likely will have to send this to the Special Mobs dev. Could someone test this on a non-LAN server and see if this still happens?

**Comment by HeyItsKairu** [comment] 2020-01-18 00:37
Can confirm that this error is reproducable. From my testing it appears that the kick occurs when killing a slime while riding it. My best guess is that the game has issues figuring out where to put the player in a situation like this, and places them at an extreme Y value. This does not seem to happen when the player stops riding the slime however, only when the slime is killed. Once it happens the affected player is no longer able to join the server, as they are instantly disconnected with the "Invalid move player packet received" error.

**Comment by HeyItsKairu** [comment] 2020-01-18 01:02
Submitted an [issue](https://github.com/FatherToast/SpecialMobs/issues/12) to the Special Mobs github.

**Comment by jaimejaime19** [comment] 2020-01-18 16:28
Hey, I just had this happen to me, but in singleplayer. I tested to see what the orange slime did, and it made me ride it. Then I killed it, and the invalid move pack error appeared and kicked me out instantly. But I can't join the world anymore since all it does is kick me out and show the move packet error. Is there any way to solve this? I have like 40 hours on the world...
Also, it sends me to the multiplayer server select weirdly. ctrl+i doesn't show anything because I am not in a world,

**Comment by HeyItsKairu** [comment] 2020-01-18 16:36
Hello, unfortunately this error is not something we can fix. It is not on our side and we will have to wait for the mod author to fix this. For a temporary fix, you could open your playerdata in an NBT Editor and fix your player's position. This is again, likely due to the slime attempting to place the player at an absurdly high Y level.

**Comment by CalaMariGold** [comment] 2020-01-30 06:13
Temporarily fixed in 2.75 by removing the Caramel Slime completely.

**Closed by CalaMariGold** 2020-01-30 06:13 UTC
