### ISSUE TITLE
[CRASH] Zombie Players

### ISSUE THREAD

**Issue by MaybeNotACow** [CalaMariGold/Rebirth-Of-The-Night#74] opened 2020-02-18 01:52 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
While fighting mobs at night, I can see a new mob in the distance, it looks like a classic Steve but slightly retextured. I assume it to be one of the Player Zombies (and it is). Approaching into combat range for melee, the monster notices me and engages. Before the first swing, the screen turns entirely gray, and the game crashes. NOTE: Game can be safely reloaded, and the Zombie will now have the appropriate skin, without a crash.

**To Reproduce**
Steps to reproduce the behavior: Presumably engage a player zombie.

**Crash Log**
Two seperate occasions.

1- 
[Log 1.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4216971/Log.1.txt)

2- 
[Log 2.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4216972/Log.2.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.75.3

**Additional context**
N/A

**Comment by democat3457** [comment] 2020-05-06 23:49
https://github.com/Corosauce/Zombie_Players/pull/12 pr here, likely not going to be merged since author is inactive

**Comment by democat3457** [comment] 2020-05-06 23:50
also either this or #296 should be closed for issue tracking purposes

**Comment by kil0byt3** [comment] 2020-05-06 23:53
Duplicate of https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/296

**Closed by kil0byt3** 2020-05-06 23:53 UTC
Labels: mod bug, needs testing
