### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Vacuousbard** [CalaMariGold/Rebirth-Of-The-Night#171] opened 2020-03-29 19:32 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
 I suddenly crash when, so i try to close the game and enter the world again and its sill crash. I think it's either because of my cobblestone generater or the season changing from winter to spring.
Sorry for my grammar, i'm not a native english speaker.
**To Reproduce**
Steps to reproduce the behavior: I don't know.

**Crash Log**
[https://paste.dimdev.org/ogibavehim.mccrash](url)

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.2

**Additional context**

Here is the link for the screenshot : [https://imgur.com/FSKIrr0](url)

**Comment by CalaMariGold** [comment] 2020-03-29 20:00
Duplicate of #54

**Closed by CalaMariGold** 2020-03-29 20:00 UTC

**Comment by Vacuousbard** [comment] 2020-03-30 13:35
I tried, it now it's said the cause is unknow.
[https://paste.dimdev.org/hatudevene.mccrash](url)
