### ISSUE TITLE
[CRASH]Dynamic Trees

### ISSUE THREAD

**Issue by Randonx** [CalaMariGold/Rebirth-Of-The-Night#247] opened 2020-04-15 04:15 UTC
**Describe the crash**
This crash has happened to me three times now, I only have log info for one of them.  In this case I was riding a Reindeer through the trees fairly close to my base, at night during a zombie invasion.

**To Reproduce**
I haven't been able to deduce what exactly is causing the event.

**Crash Log**
Crash log attached.  This crash doesn't allow me to access the create log option, so I pulled this information out of the latest.log file.

[crash.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4479074/crash.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Single player
 - Version the world was created on: 2.77.1

**Additional context**
The previous two crashes "caused by Dynamic Trees" didn't involve Reindeer, and didn't seem to have anything in common aside from walking through a wooded area.

**Comment by CalaMariGold** [comment] 2020-04-18 21:48
Issue for Dynamic Trees GitHub

**Comment by democat3457** [comment] 2020-05-07 05:40
https://github.com/ferreusveritas/DynamicTrees/issues/417

**Comment by democat3457** [comment] 2020-05-07 05:46
Opened issue https://github.com/ferreusveritas/DynamicTrees/issues/421

**Comment by democat3457** [comment] 2020-05-19 20:21
Dupe of #128.

**Closed by democat3457** 2020-05-19 20:21 UTC
