### ISSUE TITLE
[BUG] Nether Has no bedrock on the roof or floor

### ISSUE THREAD

**Issue by GoldenZdude** [CalaMariGold/Rebirth-Of-The-Night#290] opened 2020-04-26 17:14 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Bedrock is missing from the nether roof and floor

**To Reproduce**
1. go to the nether roof or floor

**Expected behavior**
there should be a nether roof and floor of bedrock

**Screenshots**
![image](https://user-images.githubusercontent.com/25122441/80314470-ad0c7700-87bf-11ea-984e-2106712ecc3f.png)
![image](https://user-images.githubusercontent.com/25122441/80314496-c1e90a80-87bf-11ea-8a94-dee6e33e3ede.png)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Probably related to dimstack

**Comment by kil0byt3** [comment] 2020-05-13 23:21
duplicate of https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/220

**Closed by kil0byt3** 2020-05-13 23:21 UTC
