### ISSUE TITLE
[CRASH]Random crash while encountered by mob (zombie)

### ISSUE THREAD

**Issue by ItzRaiderr** [CalaMariGold/Rebirth-Of-The-Night#203] opened 2020-04-07 15:30 UTC
Got this crash **twice today** with the new update: **v2.77** pre-release
The crash was caused by **_Neat mod_** and the **_zombie player mod_**?

**_Caused by:_**
When the zombie hit me, it was a jockey I couldnt see whether it was a player type zombie or not. The previous time it happened I forgot what zombie it was.

**_Reproduce:_**
Possibly getting hit by the zombies again. I'll report further.

Here are the reports:
**_First one:_**
[crash-2020-04-07_12.35.48-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4445532/crash-2020-04-07_12.35.48-client.txt)

**_Second one:_**
[crash-2020-04-07_21.18.45-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4445529/crash-2020-04-07_21.18.45-client.txt)

Fix this in the final release please. And, when the game crashes the texts look like **square/rectangle** then loads back up. And when I try to get Link for these, it says "**failed**".

--
**_Raiderr_**

**Comment by CalaMariGold** [comment] 2020-04-08 23:16
Duplicate of #74

**Closed by CalaMariGold** 2020-04-08 23:16 UTC
