### ISSUE TITLE
[BUG] Another World Perma-Crashing bug in the Aether

### ISSUE THREAD

**Issue by JuniKnytt** [CalaMariGold/Rebirth-Of-The-Night#47] opened 2020-02-05 07:21 UTC
**Describe the bug**
In the Aether, it occured in the Aether's forest biome, I have no idea what may have caused it so I'm just sending you the crash report and world download

**To Reproduce**
No idea, this time it was by accident.

**Expected behavior**
You can't boot up the world at all without it crashing like the last bug.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Modpack Version: 2.74
 -Singleplayer
 - Version the world was created on: 2.74

**Additional context**
Here are some resources if it helps, I'm sorry I'm not a MC modder I have no idea about these things.
**World DL**
[world.zip](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4157968/world.zip)
[crash-2020-02-04_23.14.11-client.txt]
**Latest Crash**
(https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4157971/crash-2020-02-04_23.14.11-client.txt)

**Comment by electrose** [comment] 2020-02-06 06:18
https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/42 Based off of the crash log it's the same issue as this one. Turn off emissive textures and see if that works. I tried the world but spawned elsewhere and when I went to the Aether all was fine.

**Comment by CalaMariGold** [comment] 2020-02-10 20:01
Duplicate of #42

**Closed by CalaMariGold** 2020-02-10 20:01 UTC
