### ISSUE TITLE
[CRASH] Upon opening furnace

### ISSUE THREAD

**Issue by Niner93R** [CalaMariGold/Rebirth-Of-The-Night#195] opened 2020-04-05 18:58 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Attempted to open a furnace from the top side, instant crash.

**To Reproduce**
Open a furnace from the top?

**Crash Log**
[crash-2020-04-05_12.56.05-client.txt](https://github.com/CalaMariGold/Rebirth-Of-The-Night/files/4434559/crash-2020-04-05_12.56.05-client.txt)

**Info (please complete the following information):**
 - Modpack Version: 2.77 Pre-release
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77 Pre-release

**Comment by CalaMariGold** [comment] 2020-04-06 19:07
Any more info? What was in the furnace? Anything to do with Arcane Archives around you?

**Comment by Niner93R** [comment] 2020-04-09 17:28
Nothing in the furnace. No arcane archives nearby let alone crafted

**Comment by kil0byt3** [comment] 2020-04-09 17:51
Interesting. Which shaders were you using

**Comment by Niner93R** [comment] 2020-04-11 18:20
@kil0byt3 It doesn't matter what shaders are used, and it seems the crash is hit or miss. It's weird.

**Comment by democat3457** [comment] 2020-05-07 05:21
Did you have a radiant tank open in jei? It appears the crash happened when it was trying to render the Radiant Tank as an Item/Ingredient in JEI, even though the screen render was a furnace.

**Comment by democat3457** [comment] 2020-06-13 03:42
Duplicate of #389

**Closed by democat3457** 2020-06-13 03:42 UTC
Labels: question
