### ISSUE TITLE
[CRASH] Crash in aether

### ISSUE THREAD

**Issue by wolfw3** [CalaMariGold/Rebirth-Of-The-Night#180] opened 2020-03-31 05:52 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
A few minutes after entering the aether, the game crashes

**To Reproduce**
1. Enter aether
2. Game will crash after a minute or two

**Crash Log**

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000062eaa276, pid=16632, tid=0x000000000000076c

 JRE version: Java(TM) SE Runtime Environment (8.0_241-b07) (build 1.8.0_241-b07)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.241-b07 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [ActualMusic.dll+0x2a276]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 D:\MultiMC\instances\Rebirth of the Night\minecraft\hs_err_pid16632.log
Compiled method (c1)  356328 13375       3       com.sun.org.apache.xerces.internal.dom.DeferredAttrImpl::synchronizeData (86 bytes)
 total in heap  [0x0000000004bac410,0x0000000004bad700] = 4848
 relocation     [0x0000000004bac530,0x0000000004bac618] = 232
 main code      [0x0000000004bac620,0x0000000004bad280] = 3168
 stub code      [0x0000000004bad280,0x0000000004bad368] = 232
 metadata       [0x0000000004bad368,0x0000000004bad3b8] = 80
 scopes data    [0x0000000004bad3b8,0x0000000004bad5a0] = 488
 scopes pcs     [0x0000000004bad5a0,0x0000000004bad6e0] = 320
 dependencies   [0x0000000004bad6e0,0x0000000004bad6e8] = 8
 nul chk table  [0x0000000004bad6e8,0x0000000004bad700] = 24

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Server
 - Version the world was created on: 2.76.2

**Comment by CalaMariGold** [comment] 2020-03-31 05:56
Duplicate of #160

**Closed by CalaMariGold** 2020-03-31 05:56 UTC
