### ISSUE TITLE
[BUG] Untextured Gneiss Items

### ISSUE THREAD

**Issue by Lieutenantcows** [CalaMariGold/Rebirth-Of-The-Night#186] opened 2020-04-02 22:08 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Gneiss Slab is untextured when broken, also Gneiss Wall has untextured particles
**To Reproduce**
Break Gneiss Cobble Slab, entity is untextured. Particles on Gneiss wall are untextured when breaking.
**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version:  Latest (as of 4/2/20)
 - Server or Singleplayer: Singelplayer
 - Version the world was created on: Latest (as of 4/2/20)

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment] 2020-04-05 04:07
Duplicate of #92

**Closed by CalaMariGold** 2020-04-05 04:07 UTC
