### ISSUE TITLE
[CRASH] Nether Invasion

### ISSUE THREAD

**Issue by Nate-idk** [CalaMariGold/Rebirth-Of-The-Night#281] opened 2020-04-24 04:36 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
I was mining around my base, then i got a nether invasion and now i can't play in my world for some reason. 

**To Reproduce**
- Have a nether invasion?

**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.

https://paste.ee/p/y595Q

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
There are 2 crash logs as i don't know which one to upload (client side and internal server side but it IS singleplayer)

**Comment by SandwichHorror** [comment] 2020-04-24 04:39
Looks to be duplicate of #69. We are probably just going to disable modded wood siding altogether as this has been a persistent pain in the ass that is not possible to remedy.

**Closed by SandwichHorror** 2020-04-24 04:39 UTC
