### ISSUE TITLE
[BUG] Eclogite brick slab turns to Black granite brick slab when picked

### ISSUE THREAD

**Issue by DapsterDan** [CalaMariGold/Rebirth-Of-The-Night#385] opened 2020-06-12 19:46 UTC
**Describe the bug**
When picked an Eclogite Brick Slab becomes a Black Granite Brick Slab.

**To Reproduce**
Place an Eclogite Brick Slab and pick it.

**Expected behavior**
Should get an Eclogite Brick Slab back.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4

**Additional context**

**Comment by SandwichHorror** [comment] 2020-06-12 20:21
duplicate of #362

**Closed by SandwichHorror** 2020-06-12 20:21 UTC
