### ISSUE TITLE
[CRASH] lighting a fire near ebony wood siding causes a game crash

### ISSUE THREAD

**Issue by Calvin304** [CalaMariGold/Rebirth-Of-The-Night#28] opened 2020-01-18 00:11 UTC
see title
https://paste.dimdev.org/livuqudifi.mccrash

**Comment by HeyItsKairu** [comment] 2020-01-18 00:18
Hello, could you please provide a crash log and perhaps a screenshot or two as well? It would help me a lot with identifying how to reproduce and fix this crash.

Thanks in advance!

**Comment by HeyItsKairu** [comment] 2020-01-18 00:59
Tested and recreated. I have submitted an [issue](https://gitlab.com/BetterWithMods/1.12/BetterWithMods/issues/1347) to the BWM page.

**Comment by CalaMariGold** [comment] 2020-02-28 03:01
Duplicate of #69

**Closed by CalaMariGold** 2020-02-28 03:01 UTC
Labels: Mod bug
