### ISSUE TITLE
[BUG] Armor bars/exhaustion disappearing seemingly at random

### ISSUE THREAD

**Issue by Dumbino** [CalaMariGold/Rebirth-Of-The-Night#282] opened 2020-04-24 15:41 UTC
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
When taking damage or holding certain items or both, all armor/armor toughness bars disappear (as if you had nothing equipped), as well as the exhaustion meter behind the hunger bars. Everything else stays put.

**To Reproduce**
I was first able to consistently reproduce it by holding a rapier in my main hand and NOTHING in my off hand. Every time I got hit while holding any type of rapier, all my armor bars would disappear for a few seconds before coming back. My friend also said that the same thing happened to him just by holding cantaloupe in his hand, without even needing to be hit, but strangely that didn't happen for me.

**Expected behavior**
For the armor bars not to disappear unless my armor actually broke. It actually makes it hard to tell sometimes when getting swarmed by goblins with those clubs that deal extra armor damage.

**Screenshots**
Not really necessary

**Info (please complete the following information):**
 - Modpack Version: Latest (2.77.1)
 - Server or Singleplayer: Server (not tested on SSP)
 - Version the world was created on: 2.77

**Additional context**
Nothing. My only guess would've been Applecore since it adds the exhaustion meter, but I don't know if that'd explain the armor bars too.

**Comment by Foreck1** [comment] 2020-04-24 15:51
We're almost certain this error is due to Quark overriding other GUI affecting mods. We're aware but thanks for reporting

**Comment by Eksekk** [comment] 2020-04-24 15:53
Something similar often happened to me after carrying something (Carry On), but only affected saturation/exhaustion meter.

**Comment by democat3457** [comment] 2020-05-08 16:53
Duplicate of #255

**Closed** 2020-05-14 19:46 UTC
